name: build and test

defaults:
  run:
    shell: bash -exo pipefail {0}

on:
  workflow_call:
    inputs:
      cuda: {type: string, required: true}
      host: {type: string, required: true}
      cpu: {type: string, required: true}
      test_name: {type: string, required: false}
      build_script: {type: string, required: false}
      test_script: {type: string, required: false}
      container_image: {type: string, required: false}
      run_tests: {type: boolean, required: false, default: true}

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build/Test ${{inputs.test_name}}
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/run-as-coder.yml
    with:
      cuda: ${{ inputs.cuda }}
      host: ${{ inputs.host }}
      name: Build/Test ${{inputs.test_name}}
      runner: linux-${{inputs.cpu}}-gpu-l4-latest-1
      image:  ${{ inputs.container_image }}
      command: |
        ${{ inputs.test_script }}
